apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: TODO
spec:
  group: TODO
  names:
    kind: Kong
    listKind: KongList
    plural: kongs
    singular: kong
  scope: Namespaced
  version: v1alpha1
