// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kong-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Kongs returns a KongInformer.
	Kongs() KongInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Kongs returns a KongInformer.
func (v *version) Kongs() KongInformer {
	return &kongInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
