// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	kongv1alpha1 "kong-operator/pkg/apis/kong/v1alpha1"
	versioned "kong-operator/pkg/client/clientset/versioned"
	internalinterfaces "kong-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kong-operator/pkg/client/listers/kong/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KongInformer provides access to a shared informer and lister for
// Kongs.
type KongInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KongLister
}

type kongInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKongInformer constructs a new informer for Kong type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKongInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKongInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKongInformer constructs a new informer for Kong type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKongInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KongV1alpha1().Kongs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KongV1alpha1().Kongs(namespace).Watch(options)
			},
		},
		&kongv1alpha1.Kong{},
		resyncPeriod,
		indexers,
	)
}

func (f *kongInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKongInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kongInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kongv1alpha1.Kong{}, f.defaultInformer)
}

func (f *kongInformer) Lister() v1alpha1.KongLister {
	return v1alpha1.NewKongLister(f.Informer().GetIndexer())
}
