// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kong-operator/pkg/client/clientset/versioned/typed/kong/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKongV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKongV1alpha1) Kongs(namespace string) v1alpha1.KongInterface {
	return &FakeKongs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKongV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
