// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kong-operator/pkg/apis/kong/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKongs implements KongInterface
type FakeKongs struct {
	Fake *FakeKongV1alpha1
	ns   string
}

var kongsResource = schema.GroupVersionResource{Group: "kong.troposhq.com", Version: "v1alpha1", Resource: "kongs"}

var kongsKind = schema.GroupVersionKind{Group: "kong.troposhq.com", Version: "v1alpha1", Kind: "Kong"}

// Get takes name of the kong, and returns the corresponding kong object, and an error if there is any.
func (c *FakeKongs) Get(name string, options v1.GetOptions) (result *v1alpha1.Kong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kongsResource, c.ns, name), &v1alpha1.Kong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kong), err
}

// List takes label and field selectors, and returns the list of Kongs that match those selectors.
func (c *FakeKongs) List(opts v1.ListOptions) (result *v1alpha1.KongList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kongsResource, kongsKind, c.ns, opts), &v1alpha1.KongList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KongList{ListMeta: obj.(*v1alpha1.KongList).ListMeta}
	for _, item := range obj.(*v1alpha1.KongList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kongs.
func (c *FakeKongs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kongsResource, c.ns, opts))

}

// Create takes the representation of a kong and creates it.  Returns the server's representation of the kong, and an error, if there is any.
func (c *FakeKongs) Create(kong *v1alpha1.Kong) (result *v1alpha1.Kong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kongsResource, c.ns, kong), &v1alpha1.Kong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kong), err
}

// Update takes the representation of a kong and updates it. Returns the server's representation of the kong, and an error, if there is any.
func (c *FakeKongs) Update(kong *v1alpha1.Kong) (result *v1alpha1.Kong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kongsResource, c.ns, kong), &v1alpha1.Kong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kong), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKongs) UpdateStatus(kong *v1alpha1.Kong) (*v1alpha1.Kong, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kongsResource, "status", c.ns, kong), &v1alpha1.Kong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kong), err
}

// Delete takes name of the kong and deletes it. Returns an error if one occurs.
func (c *FakeKongs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kongsResource, c.ns, name), &v1alpha1.Kong{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKongs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kongsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KongList{})
	return err
}

// Patch applies the patch and returns the patched kong.
func (c *FakeKongs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kong, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kongsResource, c.ns, name, data, subresources...), &v1alpha1.Kong{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Kong), err
}
