// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// KongListerExpansion allows custom methods to be added to
// KongLister.
type KongListerExpansion interface{}

// KongNamespaceListerExpansion allows custom methods to be added to
// KongNamespaceLister.
type KongNamespaceListerExpansion interface{}
