// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kong-operator/pkg/apis/kong/v1alpha1"
	scheme "kong-operator/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KongsGetter has a method to return a KongInterface.
// A group's client should implement this interface.
type KongsGetter interface {
	Kongs(namespace string) KongInterface
}

// KongInterface has methods to work with Kong resources.
type KongInterface interface {
	Create(*v1alpha1.Kong) (*v1alpha1.Kong, error)
	Update(*v1alpha1.Kong) (*v1alpha1.Kong, error)
	UpdateStatus(*v1alpha1.Kong) (*v1alpha1.Kong, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Kong, error)
	List(opts v1.ListOptions) (*v1alpha1.KongList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kong, err error)
	KongExpansion
}

// kongs implements KongInterface
type kongs struct {
	client rest.Interface
	ns     string
}

// newKongs returns a Kongs
func newKongs(c *KongV1alpha1Client, namespace string) *kongs {
	return &kongs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kong, and returns the corresponding kong object, and an error if there is any.
func (c *kongs) Get(name string, options v1.GetOptions) (result *v1alpha1.Kong, err error) {
	result = &v1alpha1.Kong{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kongs that match those selectors.
func (c *kongs) List(opts v1.ListOptions) (result *v1alpha1.KongList, err error) {
	result = &v1alpha1.KongList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kongs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kongs.
func (c *kongs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kongs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a kong and creates it.  Returns the server's representation of the kong, and an error, if there is any.
func (c *kongs) Create(kong *v1alpha1.Kong) (result *v1alpha1.Kong, err error) {
	result = &v1alpha1.Kong{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kongs").
		Body(kong).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kong and updates it. Returns the server's representation of the kong, and an error, if there is any.
func (c *kongs) Update(kong *v1alpha1.Kong) (result *v1alpha1.Kong, err error) {
	result = &v1alpha1.Kong{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kongs").
		Name(kong.Name).
		Body(kong).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *kongs) UpdateStatus(kong *v1alpha1.Kong) (result *v1alpha1.Kong, err error) {
	result = &v1alpha1.Kong{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kongs").
		Name(kong.Name).
		SubResource("status").
		Body(kong).
		Do().
		Into(result)
	return
}

// Delete takes name of the kong and deletes it. Returns an error if one occurs.
func (c *kongs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kongs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kongs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kong.
func (c *kongs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kong, err error) {
	result = &v1alpha1.Kong{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kongs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
